# Generated by Django 6.0.2 on 2026-03-02 16:41

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='subject',
            field=models.CharField(default='', max_length=200, verbose_name='Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None, verbose_name='Phone Number'),
        ),
    ]
