# Generated by Django 6.0.2 on 2026-03-02 16:41

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='About Me'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Are you an Agent?', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_buyer',
            field=models.BooleanField(default=False, help_text='Are you looking to buy a Property?', verbose_name='Buyer'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_seller',
            field=models.BooleanField(default=False, help_text='Are you looking to sell a Property?', verbose_name='Seller'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='Profile Photo'),
        ),
    ]
