#!/bin/bash

set -o errexit

set -o nounset

worker_ready(){
    celery -A real_estate inspect ping -d worker --timeout=1
}

until worker_ready; do
     >&2 echo "Waiting for worker to be ready..."
    sleep 1
done
>&2 echo "Worker is ready!"

flower \
    --app=real_estate \
    --broker="${CELERY_BROKER}" 
    
